spring:
  application:
    name: APIGATEWAY

  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          routes:
            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/movies/**

            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/bookings/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  prometheus:
    metrics:
      export:
        enabled: true
